import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { type Application, appFullName, fmtDate } from './types'

export function exportApplicationFormPDF(app: Application, filename?: string) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 40
  const name = appFullName(app) || '—'
  const pwdNumber = app.pwd_number || `PDAO-${app.id.slice(0, 8).toUpperCase()}`

  // Header
  doc.setFillColor(0, 86, 179)
  doc.rect(0, 0, pageWidth, 70, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('PDAO — PWD Application Form', margin, 30)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Persons with Disability Affairs Office', margin, 48)
  doc.text(`Application ID: ${app.id.slice(0, 8)}`, margin, 62)

  doc.setTextColor(0, 0, 0)

  let y = 90

  const sectionTitle = (title: string) => {
    doc.setFillColor(240, 245, 255)
    doc.rect(margin, y - 14, pageWidth - margin * 2, 22, 'F')
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 86, 179)
    doc.text(title, margin + 8, y)
    doc.setTextColor(0, 0, 0)
    y += 20
  }

  const twoCol = (label: string, value: string, label2?: string, value2?: string) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value || '—', margin, y + 12)
    if (label2) {
      const col2X = pageWidth / 2 + 10
      doc.setFont('helvetica', 'bold')
      doc.text(label2, col2X, y)
      doc.setFont('helvetica', 'normal')
      doc.text(value2 || '—', col2X, y + 12)
    }
    y += 28
  }

  const singleCol = (label: string, value: string) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(value || '—', pageWidth - margin * 2)
    doc.text(lines, margin, y + 12)
    y += 12 + lines.length * 12 + 8
  }

  // Personal Information
  sectionTitle('Personal Information')
  twoCol('Full Name', name, 'PWD Number', pwdNumber)
  twoCol('Date of Birth', fmtDate(app.birth_date), 'Gender', app.gender ?? '—')
  twoCol('Civil Status', app.civil_status ?? '—', 'Blood Type', app.blood_type ?? '—')
  twoCol('Contact Number', app.contact_number ?? '—', 'Email', app.email ?? '—')
  singleCol('Address', [app.address, app.barangay, app.municipality, app.province].filter(Boolean).join(', '))

  // PWD Information
  sectionTitle('PWD Information')
  twoCol('Disability Type', app.disability_type ?? '—', 'Cause', app.disability_cause ?? '—')
  twoCol('Education', app.education ?? '—', 'Occupation', app.occupation ?? '—')

  // Emergency Contact
  sectionTitle('Emergency Contact & Representative')
  twoCol('Emergency Contact', app.emergency_name ?? '—', 'Relationship', app.emergency_relationship ?? '—')
  twoCol('Contact Number', app.emergency_contact_number ?? '—', 'Representative', app.representative_name ?? '—')

  // Application Status
  sectionTitle('Application Details')
  twoCol('Status', app.status, 'Submission Date', fmtDate(app.submission_date))
  twoCol('Last Updated', fmtDate(app.last_updated), 'Remarks', app.remarks ?? '—')

  // Signature area
  y += 30
  doc.setDrawColor(180)
  doc.line(margin, y, margin + 200, y)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Applicant Signature', margin, y + 14)

  doc.line(pageWidth - margin - 200, y, pageWidth - margin, y)
  doc.text('Date', pageWidth - margin - 200, y + 14)

  // Footer
  doc.setFontSize(7)
  doc.setTextColor(150)
  doc.text(`Generated by PDAOLink — ${new Date().toLocaleString()}`, margin, doc.internal.pageSize.getHeight() - 20)

  doc.save(filename || `pwd-application-${app.id.slice(0, 8)}.pdf`)
}
